### ISSUE TITLE
Fix RNA notebook error

### ISSUE THREAD

**Issue by david4096** [BD2KGenomics/bioapi-examples#13]
There is currently a 400 bad request error in the RNA quantification notebook. We need to figure out the reason and fix it in the notebook.

**Comment by saupchurch** [comment]
There are also still some hard cded IDs that were missed in #12

**Comment by saupchurch** [comment]
It looks like the 1kg server is having a problem parsing the JSON that the notebook is sending.

The server is reporting this error:
`ERROR:ga4gh.client.client:400 {"errorCode": 1918634080, "message": "Cannot parse JSON: '{\"bioSampleId\": \"\", \"pageToken\": \"\", \"pageSize\": 0, \"rnaQuantificationSetId\": \"WyIxa2dlbm9tZXMiLCJFLUdFVVYtMSAxMDAwIEdlbm9tZXMgUk5BIFF1YW50aWZpY2F0aW9uIl0\"}'"}`

which looks like it is coming from `runSearchRequest` in `backend.py`:
`request = protocol.fromJson(requestStr, requestClass)` is throwing a `protocol.json_format.ParseError`

Could this have been introduced when biosampleID was added to the RNA API?

**Comment by david4096** [comment]
^ confirmed the version on 1kgenomes needs to be updated.

**Comment by david4096** [comment]
https://github.com/BD2KGenomics/bioapi-examples/pull/16
